In [1]:
import pandas as pd

df = pd.read_csv('AB_NYC_2019.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0

In [2]:
df.shape

(14884, 16)

In [3]:
df.price.describe()

count    14883.000000
mean       155.733118
std        247.072148
min         10.000000
25%         75.000000
50%        117.000000
75%        176.000000
max      10000.000000
Name: price, dtype: float64

In [4]:
min_threshold = df['price'].quantile(0.01)
min_threshold

np.float64(35.0)

In [5]:
df[df['price'] < min_threshold]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
469,165824,Lady only Curtain-divided room,733894,Lucy,Queens,Sunnyside,40.74000,-73.91901,Private room,33.0,44.0,31.0,2019-05-01,0.32,3.0,161.0
747,270315,Bed-stuy Royal Room,1398639,Juliet,Brooklyn,Bedford-Stuyvesant,40.68812,-73.93254,Private room,34.0,10.0,16.0,2019-03-27,0.19,3.0,216.0
776,278145,Large Room in a Huge NY apartment.,1452026,Heidi,Queens,Astoria,40.77117,-73.91905,Private room,30.0,5.0,3.0,2017-06-20,0.03,1.0,0.0
845,296844,"HISTORIC WILLIAMSBURG, BKLYN #1",839679,Brady,Brooklyn,Williamsburg,40.71653,-73.95554,Private room,30.0,3.0,24.0,2013-12-04,0.28,3.0,0.0
957,375249,Enjoy Staten Island Hospitality,1887999,Rimma & Jim,Staten Island,Graniteville,40.62109,-74.16534,Private room,20.0,3.0,80.0,2019-05-26,0.92,1.0,226.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14710,11627123,Warm and cozy,43128266,常春,Manhattan,Washington Heights,40.83463,-73.94000,Shared room,32.0,1.0,32.0,2018-11-15,0.83,3.0,332.0
14718,11637578,Spacious and sunny room for rent,61684714,Grace,Manhattan,Washington Heights,40.84248,-73.93849,Private room,26.0,7.0,0.0,NaN,NaN,1.0,0.0
14753,11659008,"Safe, comfy convenient",52347885,Nicole,Brooklyn,Flatlands,40.63052,-73.92181,Private room,34.0,2.0,91.0,2019-06-23,3.10,2.0,78.0
14760,11670639,Sunny Apartment with a balcony,61962183,Christopher,Queens,Ditmars Steinway,40.77687,-73.90386,Private room,30.0,15.0,0.0,NaN,NaN,1.0,0.0
14779,11684682,Bright sunny room in NYC!,116382,Anthony,Brooklyn,Crown Heights,40.67031,-73.94088,Private room,29.0,2.0,142.0,2019-05-19,3.54,5.0,0.0

In [6]:
max_threshold = df.price.quantile(0.99)
max_threshold

np.float64(800.0)

In [7]:
df[df['price'] > max_threshold]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
496,174966,Luxury 2Bed/2.5Bath Central Park View,836168,Henry,Manhattan,Upper West Side,40.77350,-73.98697,Entire home/apt,2000.0,30.0,30.0,2018-05-05,0.33,11.0,0.0
662,250801,Heart & Soul of Greenwich Village,1314834,Rhona,Manhattan,Greenwich Village,40.73129,-73.99944,Entire home/apt,850.0,3.0,107.0,2019-05-23,1.15,1.0,249.0
762,273190,6 Bedroom Landmark West Village Townhouse,605463,West Village,Manhattan,West Village,40.73301,-74.00268,Entire home/apt,1300.0,5.0,28.0,2018-09-25,0.31,4.0,297.0
946,363673,Beautiful 3 bedroom in Manhattan,256239,Tracey,Manhattan,Upper West Side,40.80142,-73.96931,Private room,3000.0,7.0,0.0,NaN,NaN,1.0,365.0
1105,468613,$ (Phone number hidden by Airbnb) weeks - room f,2325861,Cynthia,Manhattan,Lower East Side,40.72152,-73.99279,Private room,1300.0,1.0,0.0,NaN,NaN,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14385,11240650,Beautiful upper west side townhouse,25713263,Jess,Manhattan,Upper West Side,40.79101,-73.97961,Entire home/apt,2000.0,4.0,2.0,2016-08-23,0.06,1.0,75.0
14459,11359913,Gramercy Townhouse,53356372,Brenda,Manhattan,Gramercy,40.73546,-73.98057,Entire home/apt,1200.0,2.0,0.0,NaN,NaN,1.0,0.0
14573,11495792,Huge 1 bdrm apt; sublet March-Aug,60535622,Adela,Brooklyn,Crown Heights,40.66391,-73.95179,Entire home/apt,2100.0,120.0,0.0,NaN,NaN,1.0,363.0
14574,11495797,1br Suite - St Regis Residence Club,60535711,Bruce,Manhattan,Midtown,40.76040,-73.97410,Entire home/apt,1100.0,2.0,20.0,2019-05-16,0.53,2.0,268.0
14629,11553360,King 7,42619297,John,Brooklyn,Fort Greene,40.69413,-73.97230,Entire home/apt,999.0,2.0,94.0,2019-06-02,2.85,2.0,361.0

In [8]:
main_df = df[(df.price > min_threshold) & (df.price < max_threshold)]

In [9]:
main_df.shape

(14500, 16)

In [10]:
main_df.price.describe()

count    14500.000000
mean       141.445586
std         96.214418
min         36.000000
25%         76.000000
50%        119.000000
75%        175.000000
max        799.000000
Name: price, dtype: float64